import {strict as assert} from 'node:assert';
import {test} from 'node:test';
import {blankEvent,blankMakeup,blankConsultation,validateEvent,validateMakeup,validateConsultation,overlaps,saturday,makeSeed} from '../lib/model.ts';
test('연도 경계 일정은 허용하고 종료일 역전은 차단',()=>{const e={...blankEvent('2026-12-30'),title:'겨울 방학',end:'2027-01-03'};assert.doesNotThrow(()=>validateEvent(e));assert.throws(()=>validateEvent({...e,end:'2026-12-29'}));});
test('토요일, 30분 단위, 운영 시간과 학생 중복을 검증',()=>{const m={...blankMakeup('2026-09-26'),studentId:'s1',start:'10:30',end:'12:30'};assert.doesNotThrow(()=>validateMakeup(m,[]));assert.throws(()=>validateMakeup({...m,date:'2026-09-25'},[]));assert.throws(()=>validateMakeup({...m,start:'10:15'},[]));assert.throws(()=>validateMakeup({...m,end:'14:30'},[]));assert.throws(()=>validateMakeup(m,[{...m,id:'different',start:'11:00',end:'12:00'}]));assert.doesNotThrow(()=>validateMakeup(m,[{...m,id:'other-student',studentId:'s2'}]));assert.doesNotThrow(()=>validateMakeup({...m,date:''},[]));});
test('반개구간 교시 배정은 종료 시각을 다음 교시에 중복하지 않음',()=>{assert.equal([10,11,12,13].filter(h=>overlaps('10:30','12:30',`${h}:00`,`${h+1}:00`)).length,3);assert.equal(overlaps('10:00','11:00','11:00','12:00'),false);});
test('출석과 결과는 별도이며 결과 없는 완료는 차단',()=>{const m={...blankMakeup(),studentId:'s1',attendance:'출석' as const};assert.doesNotThrow(()=>validateMakeup(m,[]));assert.throws(()=>validateMakeup({...m,completed:true},[]));assert.throws(()=>validateMakeup({...m,attendance:'사유 결석'},[]));});
test('상담 충돌 및 결과 없는 완료 차단, 취소된 예약은 충돌 제외',()=>{const c={...blankConsultation('2026-09-21'),subjectId:'s1',target:'보호자'};assert.throws(()=>validateConsultation(c,[{...c,id:'other'}]));assert.doesNotThrow(()=>validateConsultation(c,[{...c,id:'cancelled',status:'취소'}]));assert.throws(()=>validateConsultation({...c,status:'완료'},[]));assert.doesNotThrow(()=>validateConsultation({...c,status:'완료',summary:'학습 방향 합의'},[]));});
test('유효하지 않은 일자를 차단하고 주간 이동은 토요일 유지',()=>{assert.equal(saturday('2026-09-21'),'2026-09-26');assert.throws(()=>validateEvent({...blankEvent('2026-02-30'),title:'시험'}));const seed=makeSeed();assert.equal(seed.makeups.every(m=>new Date(m.date+'T12:00:00').getDay()===6),true);assert.equal(new Set(seed.subjects.map(s=>s.id)).size,seed.subjects.length);});
