import {strict as assert} from 'node:assert';
import {test} from 'node:test';
import {blankEvent,blankMakeup,blankConsultation,validateEvent,validateMakeup,validateConsultation,overlaps,saturday,makeSeed} from '../lib/model.ts';
test('연도 경계 일정은 허용하고 종료일 역전은 차단',()=>{const e={...blankEvent('2026-12-30'),title:'겨울 방학',end:'2027-01-03'};assert.doesNotThrow(()=>validateEvent(e));assert.throws(()=>validateEvent({...e,end:'2026-12-29'}));});
test('토요일, 30분 단위, 운영 시간과 학생 중복을 검증',()=>{const m={...blankMakeup('2026-09-26'),studentId:'s1',start:'10:30',end:'12:30'};assert.doesNotThrow(()=>validateMakeup(m,[]));assert.throws(()=>validateMakeup({...m,date:'2026-09-25'},[]));assert.throws(()=>validateMakeup({...m,start:'10:15'},[]));assert.throws(()=>validateMakeup({...m,end:'14:30'},[]));assert.throws(()=>validateMakeup(m,[{...m,id:'different',start:'11:00',end:'12:00'}]));assert.doesNotThrow(()=>validateMakeup(m,[{...m,id:'other-student',studentId:'s2'}]));assert.doesNotThrow(()=>validateMakeup({...m,date:''},[]));});
test('반개구간 교시 배정은 종료 시각을 다음 교시에 중복하지 않음',()=>{assert.equal([10,11,12,13].filter(h=>overlaps('10:30','12:30',`${h}:00`,`${h+1}:00`)).length,3);assert.equal(overlaps('10:00','11:00','11:00','12:00'),false);});
test('출석과 결과는 별도이며 결과 없는 완료는 차단',()=>{const m={...blankMakeup(),studentId:'s1',attendance:'출석' as const};assert.doesNotThrow(()=>validateMakeup(m,[]));assert.throws(()=>validateMakeup({...m,completed:true},[]));assert.throws(()=>validateMakeup({...m,attendance:'사유 결석'},[]));});
test('상담 충돌 및 결과 없는 완료 차단, 취소된 예약은 충돌 제외',()=>{const c={...blankConsultation('2026-09-21'),subjectId:'s1',target:'보호자'};assert.throws(()=>validateConsultation(c,[{...c,id:'other'}]));assert.doesNotThrow(()=>validateConsultation(c,[{...c,id:'cancelled',status:'취소'}]));assert.throws(()=>validateConsultation({...c,status:'완료'},[]));assert.doesNotThrow(()=>validateConsultation({...c,status:'완료',summary:'학습 방향 합의'},[]));});
test('유효하지 않은 일자를 차단하고 주간 이동은 토요일 유지',()=>{assert.equal(saturday('2026-09-21'),'2026-09-26');assert.throws(()=>validateEvent({...blankEvent('2026-02-30'),title:'시험'}));const seed=makeSeed();assert.equal(seed.makeups.every(m=>new Date(m.date+'T12:00:00').getDay()===6),true);assert.equal(new Set(seed.subjects.map(s=>s.id)).size,seed.subjects.length);});

test('매주 단일 교사 순환, 연도 경계 및 적용일 이전 이력 보존',async()=>{const {dutyTeacher,validateTeacherOrder,migrateDemo,shift}=await import('../lib/model.ts');const data=makeSeed();data.teacherRotations=[{startDate:'2026-12-26',teachers:['정지민','이수빈','김민서']}];assert.deepEqual(Array.from({length:4},(_,i)=>dutyTeacher(data,shift('2026-12-26',i*7))),['정지민','이수빈','김민서','정지민']);assert.equal(dutyTeacher(data,'2026-12-19'),'');assert.equal(dutyTeacher(data,'2026-12-27'),'');data.teacherRotations.push({startDate:'2027-01-09',teachers:['이수빈','정지민']});assert.equal(dutyTeacher(data,'2027-01-02'),'이수빈');assert.equal(dutyTeacher(data,'2027-01-09'),'이수빈');assert.equal(dutyTeacher(data,'2027-01-16'),'정지민');assert.throws(()=>validateTeacherOrder('2026-09-25',['정지민']));assert.throws(()=>validateTeacherOrder('2026-09-26',[]));assert.throws(()=>validateTeacherOrder('2026-09-26',['정지민','정지민']));const legacy={...data,teacherSchedules:{'2026-09-26':['김민서','정지민']}};delete (legacy as Partial<typeof data>).teacherRotations;const migrated=migrateDemo(legacy);assert.equal(dutyTeacher(migrated,'2026-10-03'),'정지민');assert.deepEqual(migrated.consultations,data.consultations);assert.deepEqual(migrated.events,data.events);});
test('바로 쓴 상담 일지는 예약과 구분하고 완료에는 결과가 필요',async()=>{const {consultationState}=await import('../lib/model.ts');const c={...blankConsultation(),origin:'direct' as const,subjectId:'s1',target:'보호자'};assert.equal(consultationState(c).label,'작성 중');assert.doesNotThrow(()=>validateConsultation(c,[{...c,id:'other',origin:'reservation'}]));assert.throws(()=>validateConsultation({...c,status:'완료'},[]));assert.doesNotThrow(()=>validateConsultation({...c,status:'완료',summary:'학습 상담'},[]));assert.equal(blankEvent().staff,'');assert.doesNotThrow(()=>validateEvent({...blankEvent(),title:'담당자 없는 일정'}));});
test('상담 상태는 예약·완료·취소·미방문·미기록을 구별',async()=>{const {consultationState}=await import('../lib/model.ts');const c=blankConsultation('2026-09-21');assert.equal(consultationState(c,0).tone,'reserved');assert.equal(consultationState(c,Date.UTC(2030,0,1)).tone,'warning');assert.equal(consultationState({...c,status:'취소'}).tone,'cancelled');assert.equal(consultationState({...c,status:'미방문'}).tone,'destructive');assert.equal(consultationState({...c,status:'완료'}).tone,'success');});

test('당일 대체는 다음 주 순환과 원본 규칙을 바꾸지 않고 복원 가능',async()=>{const {setDutyOverride,dutyTeacher,registerTeacher,shift,validateTeacherOrder,migrateDemo}=await import('../lib/model.ts');const seed=makeSeed(),date=seed.makeups[0].date;const data=registerTeacher(seed,'  새교사  ');assert.equal(data.teachers.at(-1),'새교사');assert.throws(()=>registerTeacher(data,'새교사'));assert.throws(()=>registerTeacher(data,' '));assert.doesNotThrow(()=>validateTeacherOrder(date,['새교사'],data.teachers));const changed=setDutyOverride(data,date,'새교사');assert.equal(dutyTeacher(changed,date),'새교사');assert.equal(dutyTeacher(changed,shift(date,7)),dutyTeacher(seed,shift(date,7)));assert.deepEqual(changed.teacherRotations,seed.teacherRotations);assert.deepEqual(changed.archives,seed.archives);assert.equal(dutyTeacher(setDutyOverride(changed,date,''),date),dutyTeacher(seed,date));assert.throws(()=>setDutyOverride(data,shift(date,1),'새교사'));assert.throws(()=>setDutyOverride(data,date,'없는교사'));const old={...seed};delete (old as Partial<typeof old>).teachers;delete (old as Partial<typeof old>).teacherOverrides;const upgraded=migrateDemo(old);assert.deepEqual(upgraded.teacherRotations,seed.teacherRotations);assert.deepEqual(upgraded.teacherOverrides,{});assert.equal(upgraded.teachers.length,3);});
