'use client';
import {type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {CalendarDays,Search,ChevronLeft,ChevronRight,Plus} from 'lucide-react';
export function Field({label,children,required=false}: {label:string;children:ReactNode;required?:boolean}){return <div className="field"><Label>{label}{required&&<span className="text-primary">*</span>}</Label>{children}</div>;}
export function TextField({label,value,onChange,type='text',required=false,placeholder='',...props}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;placeholder?:string;min?:string;max?:string}){return <Field label={label} required={required}><Input aria-label={label} type={type} value={value} required={required} placeholder={placeholder} onChange={e=>onChange(e.target.value)} {...props}/></Field>;}
export function TextAreaField({label,value,onChange,required=false,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;placeholder?:string}){return <Field label={label} required={required}><Textarea aria-label={label} value={value} required={required} placeholder={placeholder} onChange={e=>onChange(e.target.value)} rows={3}/></Field>;}
export function Pick({label,value,onChange,options,placeholder='선택',className=''}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];placeholder?:string;className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className={className}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent position="popper">{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem value={v} key={v}>{typeof o==='string'?o:o.label}</SelectItem>})}</SelectContent></Select>;}
export function SelectField(props:Parameters<typeof Pick>[0]){return <Field label={props.label}><Pick {...props} className="w-full"/></Field>;}
export function ViewTabs({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[]}){return <Tabs value={value} onValueChange={onChange}><TabsList className="view-tabs">{items.map(i=><TabsTrigger key={i.value} value={i.value}>{i.label}</TabsTrigger>)}</TabsList></Tabs>;}
export function PageHeading({title,description,action,onAction}:{title:string;description:string;action:string;onAction:()=>void}){return <div className="page-heading"><div><h1>{title}</h1><p>{description}</p></div><Button onClick={onAction}><Plus/>{action}</Button></div>;}
export function SearchBox({value,onChange,placeholder='검색'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="search-box"><Search/><Input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>;}
export function DateNav({label,onPrev,onNext,onToday}:{label:string;onPrev:()=>void;onNext:()=>void;onToday:()=>void}){return <div className="date-nav"><Button variant="outline" onClick={onToday}>오늘</Button><Button size="icon" variant="ghost" aria-label="이전 기간" onClick={onPrev}><ChevronLeft/></Button><Button size="icon" variant="ghost" aria-label="다음 기간" onClick={onNext}><ChevronRight/></Button><h2>{label}</h2></div>;}
export function Empty({title='등록된 일정이 없습니다',description='새 일정을 추가해 시작해 보세요.',onAdd}:{title?:string;description?:string;onAdd?:()=>void}){return <div className="empty-state"><CalendarDays/><h3>{title}</h3><p>{description}</p>{onAdd&&<Button variant="outline" onClick={onAdd}><Plus/>새로 등록</Button>}</div>;}
export function Confirm({open,onClose,onConfirm,title,description,action='삭제',danger=true}:{open:boolean;onClose:()=>void;onConfirm:()=>void;title:string;description:string;action?:string;danger?:boolean}){return <AlertDialog open={open} onOpenChange={o=>!o&&onClose()}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction className={danger?'bg-destructive text-white hover:bg-destructive/90':''} onClick={onConfirm}>{action}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>;}
export function ErrorMessage({message}:{message:string}){return message?<p role="alert" className="form-error">{message}</p>:null;}
export function Status({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`status tone-${tone}`}>{children}</span>;}
