'use client';
import {useState,useEffect,useCallback,type CSSProperties} from 'react';
import {CalendarDays,BookOpen,Users,MessageSquare,RotateCcw,Download,FlaskConical,CheckCircle2,Info,Loader2} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import AcademicCalendar from './calendar';
import MakeupPage from './makeup';
import Consultations from './consultations';
import TeacherSchedule from './teacher-schedule';
import {Confirm} from './shared';
import {type DemoData,type AcademicEvent,type Makeup,type Consultation,type Subject,type Audit,uid,today,validateEvent,validateMakeup,validateConsultation,validateTeacherOrder,dutyTeacher,saturday} from '@/lib/model';
import {loadDemo,saveDemo,resetDemo,STORAGE_KEY} from '@/lib/demo-repository';
const pages=[{id:'calendar',label:'학사 일정',icon:CalendarDays},{id:'makeup',label:'토요 보강',icon:BookOpen},{id:'schedule',label:'보강 스케줄',icon:Users},{id:'consultations',label:'상담 관리',icon:MessageSquare}];
export default function Workspace(){const [data,setData]=useState<DemoData|null>(null),[page,setPage]=useState('calendar'),[error,setError]=useState(''),[reset,setReset]=useState(false),[ready,setReady]=useState(false),[saved,setSaved]=useState(''),[makeupDate,setMakeupDate]=useState(saturday());
 // Hydrate browser-only storage after SSR; the first render must match the server.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{setData(loadDemo())}catch(e){setError((e as Error).message)}setReady(true);const p=window.location.hash.slice(1);if(pages.some(x=>x.id===p))setPage(p);const onHash=()=>{const p=window.location.hash.slice(1);if(pages.some(x=>x.id===p))setPage(p)};const onStorage=(e:StorageEvent)=>{if(e.key===STORAGE_KEY){try{setData(loadDemo());toast.info('다른 탭의 변경을 반영했습니다.')}catch(e){setError((e as Error).message)}}};window.addEventListener('hashchange',onHash);window.addEventListener('storage',onStorage);return()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('storage',onStorage)}},[]);
 const navigate=useCallback((id:string)=>{setPage(id);window.location.hash=id;},[]);
 function commit(next:DemoData,message='저장했습니다.'){try{const persisted=saveDemo(next);setData(persisted);setSaved(new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}));toast.success(message)}catch(e){toast.error((e as Error).message);throw e;}}
 function upsert(kind:'events'|'makeups'|'consultations'|'subjects',item:AcademicEvent|Makeup|Consultation|Subject){if(!data)return;const before=(data[kind] as {id:string}[]).find(x=>x.id===item.id);if(kind==='events')validateEvent(item as AcademicEvent);if(kind==='makeups'){item={...item,staff:dutyTeacher(data,(item as Makeup).date)};validateMakeup(item as Makeup,data.makeups);}if(kind==='consultations')validateConsultation(item as Consultation,data.consultations);const list=before?data[kind].map(x=>x.id===item.id?item:x):[...data[kind],item];const audit:Audit={id:uid(),at:new Date().toISOString(),entity:item.id,action:before?'수정':'등록',before:before||null,after:item};commit({...data,[kind]:list,audit:[...data.audit,audit]} as DemoData);}
 function remove(kind:'events'|'makeups'|'archives',id:string){if(!data)return;const old=data[kind].find(x=>x.id===id);commit({...data,[kind]:data[kind].filter(x=>x.id!==id),audit:[...data.audit,{id:uid(),at:new Date().toISOString(),entity:id,action:'삭제',before:old,after:null}]} as DemoData,'삭제했습니다.');}
 function archive(date:string){if(!data)return;const sessions=data.makeups.filter(x=>x.date===date).map(m=>({...m,staff:dutyTeacher(data,m.date),studentName:data.subjects.find(s=>s.id===m.studentId)?.name||''}));const previous=data.archives.find(a=>a.date===date);if(previous&&JSON.stringify(previous.sessions)===JSON.stringify(sessions)){toast.info('동일한 주간 기록이 이미 보관되어 있습니다.');return;}const a={id:uid(),date,at:new Date().toISOString(),sessions};commit({...data,archives:[a,...data.archives],makeups:data.makeups.filter(m=>m.date!==date||m.kind==='정기'),audit:[...data.audit,{id:uid(),at:a.at,entity:a.id,action:'주간 보관',before:sessions,after:a}]},'기록을 보관하고 보강 목록을 초기화했습니다.');}
 function saveTeacherSchedule(date:string,teachers:string[]){if(!data)return;validateTeacherOrder(date,teachers);commit({...data,teacherRotations:[...data.teacherRotations.filter(r=>r.startDate!==date),{startDate:date,teachers}],audit:[...data.audit,{id:uid(),at:new Date().toISOString(),entity:'schedule:'+date,action:'주간 로테이션 수정',before:data.teacherRotations,after:teachers}]},'담당 선생님 순서를 저장했습니다.');}
 function exportData(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mje-demo-${today()}.json`;a.click();URL.revokeObjectURL(url);toast.success('데모 데이터 파일을 내려받았습니다.');}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'navigate_mje_workspace',description:'MJE 데모의 학사 일정, 토요 보강, 보강 스케줄, 상담 관리 화면으로 이동합니다. 데이터를 변경하지 않습니다.',inputSchema:{type:'object',properties:{page:{type:'string',enum:['calendar','makeup','schedule','consultations']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const p=(input as {page:string})?.page;if(!pages.some(x=>x.id===p))throw Error('Unknown page');navigate(p);return {page:p};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[navigate]);
 return <SidebarProvider style={{'--sidebar-width':'232px'} as CSSProperties}><AppSidebar page={page} navigate={navigate} onReset={()=>setReset(true)} onExport={exportData}/><SidebarInset className="workspace-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="md:hidden"/><span>운영 관리</span><span className="separator">/</span><strong>{pages.find(p=>p.id===page)?.label}</strong></div><div className="demo-label"><FlaskConical size={14}/><span>공유용 데모</span></div></header><div className="demo-notice"><Info size={14}/><p>가상 데이터로 체험하는 공간입니다. 변경 내용은 <strong>이 브라우저에만 저장</strong>됩니다.</p><span>실제 개인정보 입력 금지</span></div><main className="page-content" id="main-content">{!ready?<div className="loading-state"><Loader2 className="animate-spin"/>데모 데이터를 불러오는 중입니다.</div>:error?<div className="empty-state"><h1>데모를 불러오지 못했습니다</h1><p>{error}</p><Button onClick={()=>setReset(true)}>데모 초기화</Button></div>:data?<>{page==='calendar'?<AcademicCalendar data={data} onSave={e=>upsert('events',e)} onDelete={id=>remove('events',id)}/>:page==='makeup'?<MakeupPage data={data} initialDate={makeupDate} onDateChange={setMakeupDate} onSchedule={date=>{setMakeupDate(date);navigate('schedule')}} onSave={m=>upsert('makeups',m)} onDelete={id=>remove('makeups',id)} onArchive={archive} onDeleteArchive={id=>remove('archives',id)}/>:page==='schedule'?<TeacherSchedule data={data} initialDate={makeupDate} onSave={saveTeacherSchedule} onOpenMakeup={date=>{setMakeupDate(date);navigate('makeup')}}/>:<Consultations data={data} onSave={c=>upsert('consultations',c)} onSubject={s=>upsert('subjects',s)}/>}<div className="save-status"><CheckCircle2 size={13}/>{saved?`${saved} 이 브라우저에 저장됨`:'브라우저별 독립 데모 · 실제 DB 미연결'}</div></>:null}</main></SidebarInset><Toaster position="bottom-right" richColors/><Confirm open={reset} onClose={()=>setReset(false)} onConfirm={()=>{try{setData(resetDemo());setError('');setReset(false);toast.success('처음의 샘플 데이터로 되돌렸습니다.')}catch{toast.error('브라우저 저장 공간을 사용할 수 없습니다. 저장 권한을 확인해 주세요.')}}} title="데모를 처음 상태로 되돌릴까요?" description="이 브라우저에서 추가·수정한 일정과 상담 기록이 가상 샘플 데이터로 대체됩니다. 다른 사람의 데모에는 영향을 주지 않습니다." action="데모 초기화"/></SidebarProvider>;
}
function AppSidebar({page,navigate,onReset,onExport}:{page:string;navigate:(id:string)=>void;onReset:()=>void;onExport:()=>void}){const {isMobile,setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader className="brand-header"><a href="#calendar" className="brand" onClick={()=>navigate('calendar')}><span className="brand-logo">M</span><span><strong>엠제이 어학원</strong><small>운영 관리</small></span></a></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>일정 관리</SidebarGroupLabel><SidebarMenu>{pages.map(p=><SidebarMenuItem key={p.id}><SidebarMenuButton isActive={page===p.id} onClick={()=>{navigate(p.id);if(isMobile)setOpenMobile(false)}}><p.icon/><span>{p.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="demo-tools"><Button variant="ghost" onClick={onExport}><Download/>데모 데이터 내보내기</Button><Button variant="ghost" onClick={onReset}><RotateCcw/>데모 초기화</Button></div><div className="sidebar-user"><span className="avatar">체</span><div><strong>체험 관리자</strong><small>데모 · 엠제이</small></div></div></SidebarFooter></Sidebar>}
